name: CI

on:
  push:
    branches: [main]
    paths:
      - 'apps/A/**'
      - 'apps/B/**'

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Build
        run: |
          # 判断推送的文件路径，然后执行相应的构建命令
          if [[ "${{ github.event.ref_type }}" == "branch" && ("${{ github.event.ref }}" == "refs/heads/main" || "${{ github.event.ref }}" =~ ^refs\/heads\/main/) ]]; then
            if [[ "${{ github.event.repository.name }}" =~ apps\/A.* ]]; then
              echo "Building apps/A..."
              # 执行 apps/A 的构建命令
              pnpm --filter app-a run build
            elif [[ "${{ github.event.repository.name }}" =~ apps\/B.* ]]; then
              echo "Building apps/B..."
              # 执行 apps/B 的构建命令
              pnpm --filter app-b run build
            fi
          fi
        shell: bash